### ISSUE TITLE
OSError: Failed to bind family 2. Are you root?

### ISSUE THREAD

**Issue by HaiBinXiaoCheng** [kti/python-netfilterqueue#38]
VirtialBox-ubuntu
```
/home/pengb/Desktop/cateDataDemo/venv/bin/python /home/pengb/Desktop/cateDataDemo/test1.py
Traceback (most recent call last):
  File "/home/pengb/Desktop/cateDataDemo/test1.py", line 7, in <module>
    nffrqueue = NetfilterQueue()
  File "netfilterqueue.pyx", line 162, in netfilterqueue.NetfilterQueue.__cinit__ (netfilterqueue.c:4098)
OSError: Failed to bind family 2. Are you root?

Process finished with exit code 1
```

**Comment by mattfox** [comment]
Ensure you're running with root privileges. Try `sudo`.
